import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api, loadBootstrap } from '../api';

export default function Login() {
  const { login } = useAuth(); const nav = useNavigate();
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ email: '', password: '', firstName: '', lastName: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const session = mode === 'login' ? await api.login({ email: form.email, password: form.password }) : await api.register(form); login(session); await loadBootstrap(); nav(session.user.role === 'EMPLOYEE' ? '/employees' : '/payroll-dashboard', { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div id="loginScreen"><div className="loginCard"><div className="loginLeft"><div className="logo"><span className="dot" />PeoplePay360</div><div><h1>HR and payroll, connected.</h1><p>Sign in with your registered work email and password.</p></div></div><div className="loginRight"><h2>{mode === 'login' ? 'Welcome back' : 'Create account'}</h2><form onSubmit={submit}>{mode === 'register' && <div className="formGrid"><div className="field"><label>First name</label><input required onChange={e => setForm({ ...form, firstName: e.target.value })} /></div><div className="field"><label>Last name</label><input required onChange={e => setForm({ ...form, lastName: e.target.value })} /></div></div>}<div className="field"><label>Work email</label><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div><div className="field"><label>Password</label><input required type="password" minLength="8" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></div>{error && <div className="hint" style={{ color: 'var(--danger)' }}>{error}</div>}<button className="btnPrimary" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Register'}</button></form>{mode === 'login' && <button className="btn" style={{ width: '100%', marginTop: 10 }} onClick={() => nav('/forgot-password')}>Forgot password?</button>}<button className="btn" style={{ width: '100%', marginTop: 10 }} onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></div></div></div>;
}
